//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horario.WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario_Ocupado
    {
        public int ID { get; set; }
        public string Nomina { get; set; }
        public string Dia { get; set; }
        public System.DateTime Hora_Inicio { get; set; }
        public System.DateTime Hora_Fin { get; set; }
        public System.DateTime Fecha_Caducidad { get; set; }
    
        public virtual Dica Dica { get; set; }
    }
}
