//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horario.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int ID { get; set; }
        public string Nomina { get; set; }
        public System.DateTime Fecha_inicio { get; set; }
        public string Duracion { get; set; }
        public string Descripcion { get; set; }
        public string Correo_persona { get; set; }
    
        public virtual Dica Dica { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
